version: '3.7'

services:
  app-server:
    build:
      context: app-server
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    restart: always
    depends_on:
      - database
    environment:
      SPRING_DATASOURCE_URL: 'jdbc:mysql://db:3306/polls?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false'
      SPRING_DATASOURCE_USERNAME: bekmeh
      SPRING_DATASOURCE_PASSWORD: freekehnotesingsagate
    networks:
      - backend
      - frontend
  app-client:
    build:
      context: app-client
      dockerfile: Dockerfile
    ports:
      - '8000:3000'
    restart: always
    depends_on:
      - app-server
    networks:
      - frontend
  database:
    image: 'mysql:8.0.18'
    ports:
      - '3306:3306'
    restart: always
    environment:
      MYSQL_DATABASE: shoppinglist
      MYSQL_USER: bekmeh
      MYSQL_PASSWORD: freekehnotesingsagate
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - 'db-data:/var/lib/mysql'
    networks:
      - backend
volumes:
  db-data:
networks:
  backend:
  frontend: